theme: jekyll-theme-minimal
title: Prophet-600 GliGli Firmware Upgrade
description: Essential further development of the famous Teensy++ based GliGli firmware upgrade by imogen / image-et-son  
logo: /version_logo.png
